import Footer from '/components/Footer'
import Navbar from '/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Travel Web',
  description: 'Generated by neversuptou',
}

export default function RootLayout({ children,}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
          <main className='relative overflow-hidden'>
            {children}
          </main>
        <Footer />
      </body>
    </html>
  )
}
